title: "Elliot Charney"
description: "A blog about web development, Django, Python, cats, and Zen."
about: "Python, cats, and Zen."
location: "Ann Arbor, Michigan"
email: elliot.charney@gmail.com
baseurl: ""
url: "http://elliotcharney.com"
twitter_username: GETelliot
github_username:  shonin

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: en
close_btn: "Close"
home_btn: "Home"
projects_btn: "Projects"
posts_btn: "Posts"
imprint_btn: "About"
name_badge: "a post by"
rss_badge: "Subscribe feed!"

# build settings
markdown: kramdown

# exclude files
exclude:
  - LICENSE
  - README.md
